version: "3.0"

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    ports:
      - "9000:9000"
  mariadb:
   build: ./requirements/mariadb
   container_name: mariadb
   env_file: .env
   ports:
    - "3306:3306"
  nginx:
   build: ./requirements/nginx
   container_name: nginx
   env_file: .env
   ports:
    - "433:433"

