version: "3.0"

services:
  wordpress:
    container_name: wordpress
    image: wordpress:1337
    build: ./requirements/wordpress
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - "wordpress:/var/www/html/"
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb
  mariadb:
      container_name: mariadb
      image: mariadb:1337
      build: ./requirements/mariadb
      env_file: .env
      ports:
       - "3306:3306"
      volumes:
       - "mariadb:/var/lib/mysql"
      networks:
       - inception
      restart: on-failure
  nginx:
    container_name: nginx 
    image: nginx:1337
    build: ./requirements/nginx
    env_file: .env
    ports:
     - "443:443"
    volumes:
      - "wordpress:/var/www/html/"
    networks:
     - inception
    restart: on-failure
    depends_on:
      - wordpress
  redis:
    container_name: redis
    image: redis:1337
    build: ./requirements/bonus/redis
    volumes:
      - "wordpress:/var/www/html/"
    networks:
     - inception
    restart: on-failure
    depends_on:
      - wordpress
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:1337
    env_file:
      - .env
    ports:
      - "1337:1337"
    networks:
      - inception
    restart: on-failure
    depends_on:
      - mariadb


volumes:
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
        #change volume device to /home/megrisse/data/mariadb
          device: /home/megrisse/data/mariadb
          type: volume
          o: bind
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
        #change volume device to /home/megrisse/data/wordpress
          device: /home/megrisse/data/wordpress
          type: volume
          o: bind

networks:
  inception: